### ISSUE TITLE
Legacy warning

### ISSUE THREAD

**Issue by boks1971** [jeremyjh/dialyxir#240]
Saw this in my project. Thanks for the pointer to file a bug here. Cut and paste of message

```
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Failed to parse warning:
[{:"(", 1}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'h'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 'd'}, {:::, 1}, {:int, 1, 0}, {:.., 1}, {:int, 1, 4095}, {:",", 1}, {:atom_part, 1, 'c'}, {:atom_part, 1, 'l'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 's'}, {:atom_part, 1, 's'}, {:::, 1}, {:int, 1, 0}, {:.., 1}, {:int, 1, 3}, {:")", 1}, {:->, 1}, {:int, 1, 0}, {:.., 1}, {:int, 1, 16383}]

Legacy warning:
example.ex:154: Type specification 'Elixir.Example':type(method::0..4095,class::0..3) -> 0..16383 is a supertype of the success typing: 'Elixir.Example':type(1,0 | 2 | 3) -> 1 | 17 | 257 | 273
```
Although the function gets used with specific values, the input can be a range of values which could be used later. So, defining something that is generic causes the super-typing error + it also puts out the `Failed to parse warning` message.

I am using the 1.0.0-rc3 package from hex.pm

**Comment by asummers** [comment]
Interesting. Thanks for the report.

**Comment by asummers** [comment]
@jeremyjh I'll adjust the verbiage on that message too so it directs people to the proper library, depending on where the error comes from.

**Comment by asummers** [comment]
Didn't forget about you @boks1971 -- I have a tentative fix for this locally. Will try to get this resolved in next few days.

**Comment by boks1971** [comment]
Thank you @asummers . Really appreciate it.

**Comment by asummers** [comment]
@boks1971 I think I fixed this. Can you try with rc4?

**Comment by boks1971** [comment]
@asummers Thank for looking into this.

Unfortunately, I cannot find the exact example I gave you before as I have done a lot of changes to my project and that example is no more there. But, another complaint which was happening is still happening with `rc.4` (that code is still there. Actually, even in that code I found my mistake of type specing and once I fix that there are no more warnings. But, I do not know if a wrong typespec should emit a warning like this.)

```
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Failed to parse warning:
[{:"(", 1}, {:_, 1}, {:atom_part, 1, 'h'}, {:atom_part, 1, 'i'}, {:atom_part, 1, 's'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 'g'}, {:atom_part, 1, 'r'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'm'}, {:atom_part, 1, '@'}, {:int, 1, 2}, {:::, 1}, {:"[", 1}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'n'}, {:atom_part, 1, 'y'}, {:"(", 1}, {:")", 1}, {:"]", 1}, {:",", 1}, {:_, 1}, {:atom_part, 1, 't'}, {:atom_part, 1, 'o'}, {:atom_part, 1, 't'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'l'}, {:_, 1}, {:atom_part, 1, 's'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'p'}, {:atom_part, 1, 'l'}, {:atom_part, 1, 'e'}, {:atom_part, 1, 's'}, {:atom_part, 1, '@'}, {:int, 1, 1}, {:::, 1}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'n'}, {:atom_part, 1, 'y'}, {:"(", 1}, {:")", 1}, {:",", 1}, {:int, 1, 1}, {:atom_part, 1, '.'}, {:int, 1, ...}, {:atom_part, ...}, {...}, ...]


Legacy warning:
example.ex:388: The call 'calculate_average(_histogram@2::[any()],_total_samples@1::any(),1.0e-3,float()) breaks the contract (histogram::t_histogram(),total_samples::non_neg_integer(),bin_offset::float(),bin_size::float()) -> float()
```

In the example above, my mistake is in the type of first argument. I have given it as `t_histogram` which is a map of `%{integer => integer}`, but the correct type is a list of tuples (i.e. map represented as a list). Once I make that correction, no more dialyzer errors.

**Comment by asummers** [comment]
Just for my note later:

Bug in erlex parsing scientific notation exhibited by:

```
  test "scientific notation numbers are printed appropriately" do
    input = ~S"""
    (1.0e-3)
    """

    pretty_printed = Erlex.pretty_print_contract(input)

    expected_output = "(1.0e-3)"
    assert pretty_printed == expected_output
  end
```

**Comment by asummers** [comment]
Sigfigs are now handled in Erlex master and will be available in a future release in the next week or so.
